prompts = [
"You wake up one morning to find out that you get to move to any planet of your choosing.",
"Your wife is a droid.",
"Every day, you get one hour to revisit any moment from your life. What do you pick?",
"Gravity no longer exists.",
"You are chosen to go on the first ever recreational space journey.",
"After people die, their spirits can be brought back from death but at the cost of one random human life. Is it worth it?",
"Everyone in the world has the ability to read thoughts. Except for one person.",
"You have to power to build one separate planet. How do you build it? Who gets to live there?",
"What team do you gather to fight the largest alien and terrorist threat on Earth?",
"The world is dying. In order to save it, you've been commanded to sacrifice yourself to an invading alien group.",
"You are the first person able to breathe in outer space.",
"A rare form of cancer is the newest superbug. With a team of scientists, you all must find a cure before the population is wiped out.",
"Human beings begin to find themselves growing extra limbs as global warming amps up.",
"It turns out humans have been the aliens all along.",
"You are in charge of a secretive government agency that aligns people's fates. Their livelihood is entirely up to you and what you want to do with it.",
"Technology becomes illegal.",
"All plant life on the planet is wiped out, except for in Florida.",
"You are one of the mechanics on the first ever self-flying airplane.",
"Walking through the woods one day, you come across a small animal that has the ability to instantaneously clone itself.",
"Your whole family has fought in the space military, but you've decided to no longer take part in it.",
"In an alternate universe where global warming has ruined the planet, you've spent your entire life living in an airplane on autopilot.",
"You're a 15-year-old in the middle of a zombie apocalypse. However, a cure has been found that not only rids the infected person of the virus before they turn but prevents it altogether. Only one problem... Your parents are anti-vaxxers.",
"Nasa engineers monitor the curiosity rover's actions. All seems normal until the robot suddenly changes its course. The scientists attempt to correct it over and over until they suddenly receive a transmission from the rover: 'Will Save Oppy'",
"What if a nuclear submarine was ordered to launch their nuclear arsenal onto the world?",
"What if the world we live in is actually a computer simulation?",
"What if the past and present timelines began to merge?",
"What if your stepfather or stepmother is actually your future self?",
"What if the sun began to die?",
"What if the universe as we know it is actually someone's imagination?",
"Everyone on earth begins to experience universal amnesia.",
"The year is 2200. What does the world look like to you?",
"In the future, we no longer require water, air, or food. We are a super efficient team of robots.",
"What do you think happens when the grid goes down?",
"Describe your perfect utopian world.",
"Your penpal lives on the opposite side of the universe.",
"Aliens who only communicate with sign language invade. To avoid war, our governments must engage a vastly marginalized portion of the human population: the hearing-impaired. ",
"A rogue planet with strange properties collides with our sun, and after it's all over, worldwide temperature falls forty degrees. Write from the perspective of a someone trying to keep his tropical fruit trees alive. ",
"Ever read about the world's loneliest whale? Write a story in which he's actually the survivor of an aquatic alien species which crashed here eons ago, and he's trying very hard to learn the 'local' whale language so he can fit in. Write from his perspective the first time he makes contact. ",
"An alien planet starts receiving bizarre audio transmissions from another world (spoiler: they're from Earth). What does it mean? Are they under attack? Some think so...until classic rock 'n' roll hits the airwaves, and these aliens discover dancing. Write from the perspective of the teenaged alien who first figures it out. ",
"Take anything we find normal today (shopping malls, infomercials, products to remove facial hair, etc.) and write a story from the perspective of an archeologist five thousand years in the future who just unearthed this stuff, has NO idea what any of it was for, and has to give a speech in an hour explaining the historical/religious/sociological significance. ",
"House cats are aliens who have succeeded in their plan to rule the world. Discuss.",
"A high schooler from fifteen hundred years in our future is assigned a one-page writing project on a twenty-first century person's life based entirely on TV commercials. Write the beginning of the essay. ",
"Time travel works, but only once in a person's life. Write from the perspective of someone who chooses to go back in time, knowing they can never return. Where do they go and why? ",
"So yeah, ancient Egypt really was 'all that' after all, and the pyramids turn out to be fully functional spaceships (the limestone was to preserve the electronics hidden inside). Write from the perspective of the tourist who accidentally turns one on. ",
"Ten years from now, scientists figure out how to stop human aging and extend life indefinitely-but every time someone qualifies for that boost, someone else has to die to keep the surplus population in check. Oh, it's all very humane; one's descendants get a huge paycheck. Write from the perspective of someone who just got a letter in the mail saying they're the one who has to die. ",
"In the future, neural implants translate music into physical pleasure, and earphones ('jacking in') are now the drug of choice. Write either from the perspective of a music addict, OR the Sonforce agent (sonance + enforcer) who has the job of cracking down. ",
"It's the year 5000. Our planet was wrecked in the great Crisis of 3500, and remaining human civilization survives only in a half dozen giant domed cities. There are two unbreakable rules: strict adherence to Life Quality (recycling doesn't even begin to cover these laws), and a complete ban on reproduction (only the 'worthy' are permitted to create new humans). Write from the perspective of a young woman who just discovered she's been chosen to reproduce-but she has no interest in being a mother. ",
"In the nineteenth century, there's a thriving trade in stolen archeological artifacts. Write a story from the perspective of an annoyed, minimum-wage employee whose job is traveling back in time to obtain otherwise unobtainable artifacts, then has to bring them back to the present (the 1800s, that is) and artificially age them before they will sell. ",
"Steampunk! Write a story from the perspective of a hot air balloon operator who caters to folks who like a little thrill... which means she spends half her time in the air shooting down pterodactyls before the paying customers get TOO scared. "
    
    ]